### ISSUE TITLE
2.1. Collection "Posts" - CRUD

### ISSUE THREAD

**Issue by tungnt-580** [ngminhtrung/fcchn-blog-backend#24]
* See here API interface here https://github.com/ngminhtrung/fcchn-blog-backend/blob/master/readme-datamodel.md#b%E1%BA%A3ng-li%E1%BB%87t-k%C3%AA-http-routes-v%C3%A0-verbs. Update doc if there are something not make sense.
* Point router
* Write controller function
* Write model function if needed
* Test to make sure it work properly

**Comment by ngminhtrung** [comment]
Done by @vutung3196
