### ISSUE TITLE
Lỗi tên thành viên đóng góp cho phần Back-end.

### ISSUE THREAD

**Issue by vutung3196** [ngminhtrung/fcchn-blog-backend#50]
Hiện giờ ở phần file readme.md, đang bị lỗi tên thành viên đóng góp cho phần Backend. Cụ thể là tên "Vũ Thanh Tùng" cần sửa lại thành "Vũ Tùng". Mọi người xem giùm em nhé.

**Comment by ngminhtrung** [comment]
@vutung3196: Trời em cứ tạo pull request để merge phát fix luôn. Người ta vẫn yêu cầu sửa chính tả kiểu này mà.

**Comment by vutung3196** [comment]
Vâng, để em tạo pull request.
