### ISSUE TITLE
[Todo 2018.01.17] Cập nhật công việc cần làm

### ISSUE THREAD

**Issue by ngminhtrung** [ngminhtrung/fcchn-blog-backend#9]
## Tham dự:

1. Nguyễn Thế Phụng Long
2. Vũ Tùng
3. Nguyễn Thế Tùng
4. Nguyễn Minh Trung
5. Khắc Thành

## Nội dung thảo luận
- Tính năng "*like*" cho *post* -> Làm giống Medium, tối đa 50 like/ user.
- Tính năng "*like*" cho *comment* -> 0/1.
- Tách thành 5 bảng: Users, Posts, Comments, và Likes
- Làm lại bảng mô tả: **Resouce**, **Actions**, **Routes**, **HTTP Methods/ Verbs**, **Description**, và **Parameters**.

## Danh sách các công việc cần làm:

1. Viết lại sample JSON của data model --> Deadline: 21.01.2018 Trung (@ngminhtrung)
2. Tạo project folder, gitignore, package.json --> Deadline: 23.01.2018 Long (@thelonglqd) 
3. Chuyển bảng trên từ Google Spreadsheet sang markdown --> Deadline: 21.01.2018 Trung (@ngminhtrung)

**Comment by tungnt-580** [comment]
Issue này thế nào nhỉ. Qua due date hết rồi, anh @ngminhtrung, anh @thelonglqd l

**Comment by ngminhtrung** [comment]
@tungnt-580 : coi như đã done.
